### ISSUE TITLE
Clicking in color space does not always select a color 

### ISSUE THREAD

**Issue by avermeil** [kleinfreund/vue-accessible-color-picker#13]
First of all, thanks for building this great library! It's working very well for us, but there's one small detail I think would make it perfect :)

## Steps to reproduce

When clicking on the color space to select a color, nothing happens until the mouse is moved. As in, you need to click-and-drag to move the `color-space-thumb`, not just click. 

This is fine once you know the trick, but at first it feels like the colorpicker doesn't work correctly; It feels like only some clicks are registering.

I've tried using a mouse and a trackpad, both have the same issue.

In contrast, the native chrome color picker (as can be demoed [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color)) moves the selector on click immediately.

## Environment

The issue is live here: https://vue-accessible-color-picker.netlify.app/

Here's a screen recording. The circle shows up around my cursor when I click.
https://user-images.githubusercontent.com/1063061/140169496-188317b2-62f0-482a-bb6e-927870d57673.mov

**Comment by kleinfreund** [comment]
Hello @avermeil. First of all, thank you for the kind words and also for filing a complete and comprehensive bug report.

I could reproduce the issue easily and have published a fix for it in https://github.com/kleinfreund/vue-accessible-color-picker/commit/c68ea8a0bc838c0578b7dba4fe58f5a63025b21b. The fix is released with version 3.0.1 of the package. Please let me know if it doesn’t work correctly still. I will now also update the demo website.

Thank you. :)

**Comment by avermeil** [comment]
Hi @kleinfreund, I can confirm that `3.0.1` fixed the problem! Thanks for the quick turnaround 🥳
