### ISSUE TITLE
:visible-formats="['hex']" does not work

### ISSUE THREAD

**Issue by ac-saro** [kleinfreund/vue-accessible-color-picker#23]
version 4.0.6

```
<ColorPicker :visible-formats="['hex']" />
```

## Current result
![image](https://user-images.githubusercontent.com/15857631/194378375-5e4aa24f-cb5c-4ad2-87b8-3797ae11af57.png)

## Expected result
![image](https://user-images.githubusercontent.com/15857631/194378484-3e6ec7fe-a1e6-4ed6-b3f5-095b92817846.png)

**Comment by kleinfreund** [comment]
Thank you for reporting this. As a workaround, you can additional provide the `defaultFormat` prop and set it to `'hex'`. Nonetheless, I've implemented a fix for this in https://github.com/kleinfreund/vue-accessible-color-picker/commit/9530d37455933a58af8718527bea6844effa8fdd. The fix was published in [v4.0.7](https://github.com/kleinfreund/vue-accessible-color-picker/releases/tag/v4.0.7).
